### ISSUE TITLE
Importing named export

### ISSUE THREAD

**Issue by thangngoc89** [rescript-association/genType#113]
I'm using gentype.import for binding to React components. The library uses named export extensively so it would be lovely to have named export available. Example output code:

```
import { Foo } from "bar"
```

**Comment by cristianoc** [comment]
This should be doable by adding meaning to the annotation `[@genType.as "Foo"]`.
Similar to what was done for importing simple values: https://github.com/cristianoc/genType/commit/df0d810eb49d166759d8fdda2bb6623d786b0979.

**Comment by thangngoc89** [comment]
@cristianoc could you please make a new release with this? I'm currently using a hack to avoid this limitation
