### ISSUE TITLE
genType doesn't read bsconfig module flag

### ISSUE THREAD

**Issue by adnelson** [rescript-association/genType#505]
I was running into an issue where gentype would generate

```javascript
const Curry = require('bs-platform/lib/es6/curry.mjs');
```

rather than

```javascript
var Curry = require("bs-platform/lib/js/curry.js");
```

Which is what appears in `.bs.js` files. This resulted in a very unhappy compiler (`tsc`):

```
[Node] ./node_modules/bs-platform/lib/es6/curry.mjs:3
[Node] import * as Caml_array from "./caml_array.mjs";
[Node] ^^^^^^
[Node] 
[Node] SyntaxError: Cannot use import statement outside a module
```

My `bsconfig.json` specifies `"commonjs"` for `.bs.js` files, 

```json
{
  "package-specs": [
    {
      "module": "commonjs",
      "in-source": true
    }
  ],
  ...
}   
```

Looking over `Config_.re` in this project, I saw that the fix was to put it in my `gentypeconfig`:

```json
{
  "gentypeconfig": {
    "module": "commonjs"
    ...
  },
  ...
}
```

I think if `gentype` used whatever's in `package-specs`, with the ability to override it on the `gentypeconfig`, it would make for a little more intuitive experience.

Thoughts?

**Comment by cristianoc** [comment]
@adnelson thanks for the suggestion! It makes sense.
