### ISSUE TITLE
Generate enum type from polyvar?

### ISSUE THREAD

**Issue by adnelson** [rescript-association/genType#518]
If I have some code like this:

```reason
[@genType]
type color = [ | `Red | `Blue ];
```

then gentype will create a binding like

```typescript
export type color = 
    "Red"
  | "Blue";
```

I was looking at the options and I'm not sure if I missed it but is there a way to generate an enum like

```typescript
export enum color {
  "Red" = "Red",
  "Blue" = "Blue"
};
```

?

**Comment by cristianoc** [comment]
@adnelson there are no options to generate enums.

**Comment by adnelson** [comment]
Would this be desirable? The use case I'm looking at now is the nexus graphql schema library, which can take a JS enum and produce a graphql enum type.

Hypothetically:

```reason
[@genType.enum]
type color = [ | `Red | `Blue ];
```

Or alternatively, via a flag in `gentypeconfig` like

```json
{
  "gentypeconfig": {
    "variantStyle": "enum"
  }
}
```

If this is something you might be interested in, I can try my hand at implementing it.

**Comment by cristianoc** [comment]
@adnelson how about starting by exploring the design, then see how that fits.

A couple of first questions:
- What variants map to enums? Only variants without payload?
- When looking at enums, I see things like `Up = "UP"`, not identical `"UP" = "UP"`. And more in general, only a subset of enums will be representable.
- Is there any runtime conversion required to operate with enums? 
- What about the Flow back-end.

**Comment by adnelson** [comment]
I'll circle back on the design, my initial thoughts regarding your Q's:

* Only variants without a payload supported
* Simplest would be to only support enums where the field name and the value match -- this is how all of our enums look anyway, but if need be, a ppx annotation could solve that (e.g. pseudo: ``| [@genType.as "UP"] `Up``)
* I don't think so. Given code like this:

```typescript
export enum MyEnum {
  Foo = "Foo",
  Bar = "BAR",
};
```

`tsc` will emit code like this

```
var MyEnum;
(function (MyEnum) {
    MyEnum["Foo"] = "Foo";
    MyEnum["Bar"] = "BAR";
})(MyEnum || (MyEnum = {}));
;
```

Which means that at runtime `MyEnum.Foo === "Foo"`.

* I think flow only supports the union syntax, so flow users simply wouldn't need this feature. But if desired, code such as described [here](https://www.digitalocean.com/community/tutorials/react-flow-enums) could be generated

```javascript
const myEnumValues = {
  Foo: "Foo",
  Bar: "BAR",
};

type MyEnum = $Keys<typeof myEnumValues>;
```

**Comment by cristianoc** [comment]
Looks like in TS a value of enum type also has union type, but not the other way round. Not sure why that is the case if the runtime representation is the same.

**Comment by cristianoc** [comment]
OK looks like ` color.Red` is nominally typed, so it's a different type than `Red`.

**Comment by cristianoc** [comment]
Poly variants are structurally typed, so mapping them to a nominal type has a few footguns, e.g. you can't rely on type inference.
E.g. if you export ``` @genType let red =`Red ``` it won't have type `color`.

**Comment by cristianoc** [comment]
@adnelson could you explain the use case a bit more in detail?

**Comment by cristianoc** [comment]
If the use case is worth it, it could be an experimental feature.

**Comment by cristianoc** [comment]
Happy to continue the convo if there's still interest? Or we can close this otherwise.

**Comment by ryyppy** [comment]
This repository is being archived. If you feel like the issue still relevant, please re-create it in the [compiler repo](https://github.com/rescript-lang/rescript-compiler). Thanks!
