### ISSUE TITLE
Is in planning to support suffix with ".mjs"?

### ISSUE THREAD

**Issue by koji-k** [rescript-association/genType#521]
gentype generates `tsx` file assuming `bs.js`.
(I know this is limitation of gentype)

like:

```
// @ts-ignore: Implicit any on import
import * as HelloRescriptBS__Es6Import from './HelloRescript.bs';
```

`HelloRescript.bs.js` does not exists. there is `HelloRescript.mjs`.

I want to use gentype with TypeScript for Svelte application.
And for test `bs-jest`.

For Svelte, ReScript must be builded as es6.
And suffix must be ".mjs" for bs-jst.

I hope that some time be supported "mjs".

**Comment by cristianoc** [comment]
Like this?   https://github.com/rescript-association/genType/pull/522

**Comment by koji-k** [comment]
Yes！！
Thank you very much for your so quick response and action!

I tried to build current code of master branch of genType.
and i tested with the created GenType.exe my Svelte application and Jest tests.
Everything worked fine!
I can not wait for this commit to be oficially released.

rellay thanks :)

**Comment by cristianoc** [comment]
Fantastic.
I guess you're unblocked and don't need a new release straight away.
