### ISSUE TITLE
Wrong type generated for variant

### ISSUE THREAD

**Issue by erikras** [rescript-association/genType#535]
### TLDR;

My event variant type is treated as an integer in JS, and a string in TS.

### My ReScript

```reason
export type event = Increment | Decrement

let inc = Increment
```

### Generated JavaScript

```js
var inc = /* Increment */ 0;

export { inc }
```

### Generated TypeScript

```ts
export type event = "Increment" | "Decrement";
```

### Versions

```json
{
  "gentype": "^3.48.0",
  "bs-platform": "9.0.2",
}
```

**Comment by cristianoc** [comment]
`inc` is not exported, add a `@genType` to it (or `export`, but that notation is being phased out) and the conversion will take place.

**Comment by erikras** [comment]
That's not the problem. The generated `event` type is still `string` in TypeScript.

It would be nice if you would try running it yourself. It's just two lines.

**Comment by cristianoc** [comment]
```rescript
const $$toJS686827308: { [key: string]: any } = {"0": "Increment"};

// @ts-ignore: Implicit any on import
import * as ABS__Es6Import from './A.bs';
const ABS: any = ABS__Es6Import;

// tslint:disable-next-line:interface-over-type-literal
export type event = 
    "Increment"
  | { tag: "Decrement"; value: number };

export const inc: event = typeof(ABS.inc) === 'object'
? {tag:"Decrement", value:ABS.inc._0}
: $$toJS686827308[ABS.inc];
```

This ^ is the conversion. You use it as  `string` from TS, and keeps the internal representation on the ReScript side.

You might want to use `#This | #That` to have the same runtime representation, and zero conversion, on the TS and ReScript sides.

**Comment by erikras** [comment]
Here is a reproduction of my problem.
https://github.com/erikras/rescript-gentype-bug

**Comment by cristianoc** [comment]
@erikras can you add `@genType` to the type definition
```rescript
@genType
type machine<'state, 'event> = {
```

It should solve your issue.

That said, ideally there should be a detection for this. This being: a type not exported is used indirectly from a function exported in another module, so it's implicitly exported.

**Comment by erikras** [comment]
That did it! Thank you!

Very counter-intuitive that to fix type generation in `counter.res`, I need a `@genType` in `Machine.res`.

**Comment by cristianoc** [comment]
> Very counter-intuitive that to fix type generation in counter.res, I need a @genType in Machine.res.
Indeed.
