### ISSUE TITLE
Enhancement: Use typescript "import type" syntax for type imports

### ISSUE THREAD

**Issue by chrischen** [rescript-association/genType#549]
Please excuse the old ReasonML syntax...
```reason
[@genType.import "mongodb"]
[@genType.as "ObjectId"]
type t;
```

This generates

```ts
import {ObjectId as $$ObjectId_t} from 'mongodb';
```

Which works, and is correct, but in some cases can cause cyclical imports if only types are needed (this is a third party library so it wouldn't happen, but can happen with own library).

This syntax would be better as it's only compile-time and stripped at runtime.
```ts
import type {ObjectId as $$ObjectId_t} from 'mongodb';
```

**Comment by cristianoc** [comment]
Thanks, that's a nice suggestion.
