### ISSUE TITLE
Could Not Read Multiple Files

### ISSUE THREAD

**Issue by Mastermind497** [rescript-association/genType#550]
When building—only when genType is installed—I am greeted with this error which I can not solve:
![image](https://user-images.githubusercontent.com/39387439/118677176-0c259b00-b7ca-11eb-8e51-b68885d3fca9.png)

**Comment by cristianoc** [comment]
Would you create a small repro? That message seems to be coming from the compiler.
Also, worth doing a deep clean and build first.

**Comment by cristianoc** [comment]
Feel free to re-open with a repro.
