### ISSUE TITLE
Rescript react ariaLabel prop is not getting transformed to "aria-label" in tsx

### ISSUE THREAD

**Issue by srikanthkyatham** [rescript-association/genType#560]
Hi

I am using 

"rescript": "^9.1.2",
"gentype": "^4.0.0"

When I write the binding like the following
`
module Tracker = {
  @genType.import(("tracker", "Tracker")) @react.component
  external make: (
    ~ariaLabel: string=?,
  ) => React.element = "Tracker"
}
`

The generated gen.tsx is

`
export const TrackerTypeChecked: React.ComponentType<{
  readonly ariaLabel?: string
}> = TrackerNotChecked;
`

I am expecting the gen.tsx to be
`
export const TrackerTypeChecked: React.ComponentType<{
  readonly "aria-label"?: string
}> = TrackerNotChecked;
`

I have followed the guidelines here https://rescript-lang.org/docs/react/latest/components-and-props#handling-invalid-prop-names-eg-keywords

DId I miss anything, please help

**Comment by cristianoc** [comment]
I'm not sure the generated `.bs.js` treats aria the way you'd like to begin with.
It does treat aria in a special way when used for `<div ariaLabel="..." />`, not sure about externals.
Can you add a use of those externals see what the `.bs.js` for the use looks like?

**Comment by srikanthkyatham** [comment]
Hi @cristianoc 

Here is the bs.js 
`
React.createElement("header", undefined, React.createElement(Opux.ProgressTracker.make, {
                      currentStep: currentStep,
                      steps: 5,
                      ariaLabel: "tracker"
                    })), React.createElement("main", undefined, children));
}
`

**Comment by cristianoc** [comment]
See: "ariaLabel" is not modified in the JS.

**Comment by srikanthkyatham** [comment]
Hi

Yes I see it is not modified any other alternative approaches to this issue

**Comment by cristianoc** [comment]
Can you ask in the forum? Song he answer will be available to others.

**Comment by cristianoc** [comment]
This is not about genType.

**Comment by srikanthkyatham** [comment]
Sure thanks I will

**Comment by srikanthkyatham** [comment]
I have posted in the forum https://forum.rescript-lang.org/t/rescript-react-arialabel-prop-is-not-getting-transformed-to-aria-label-with-non-dom-elements/1767
