### ISSUE TITLE
Invalid import path for namespace-enabled module

### ISSUE THREAD

**Issue by kgtkr** [rescript-association/genType#573]
example repo: https://github.com/kgtkr/gentype-module-bug

`module-name/SubModuleName.gen` is correct instead of `module-name/ModuleName.gen`

## related?
* #336

**Comment by ryyppy** [comment]
This repository is being archived. If you feel like the issue still relevant, please re-create it in the [compiler repo](https://github.com/rescript-lang/rescript-compiler). Thanks!
