### ISSUE TITLE
Unused variables in function with gentype tag makes rescript compiler infinitely recompile.

### ISSUE THREAD

**Issue by not-rusty** [rescript-association/genType#576]
Hello there!

As the title says, whenever there's a function with an unused variable like this:

```rescript
@genType
let getItemIndicators = (arg: string) => {
  failwith("unimplemented")
}
```

The rescript compiler gets into a strange recompile infinite loop.

Demo of the bug: https://github.com/not-rusty/gentype-spin-like-crazy

I must add that  adding an underscore stops the compiler from entering the recompiling loop, but obviously that's not preferable :)

Other than that, thanks for this tool guys! This is so smooth compared to f# + fable.

**Comment by not-rusty** [comment]
Compiler versions:

    "gentype": "^4.1.0",
    "rescript": "^9.1.4",

**Comment by cristianoc** [comment]
@not-rusty looks like `"generatedFileExtension": ".gen.ts"` confuses the rescript build in the presence of the warning. The default extension `.tsx`seems fine.

**Comment by not-rusty** [comment]
@cristianoc Just checked today that recompiles with any warning, not only `unused variable` warnings.

**Comment by cristianoc** [comment]
Looks like the compiler mechanism for dealing with warnings (in general) is currently not happy with extensions it does not expect. (The compiler does not know about specific genType settings).

**Comment by searleser97** [comment]
having the exact same issue as @not-rusty

**Comment by not-rusty** [comment]
Is this at some point getting solved, or it is really difficult to fix? This alone makes my rescript nodejs migration really hard, as most transpilers have really weird interactions with `.tsx` files on the nodejs world.

**Comment by bobzhang** [comment]
@not-rusty this is also filed here https://github.com/rescript-lang/rescript-compiler/issues/5303, it will be fixed in next release.
As a work around, you can turn warn-as-error.

**Comment by not-rusty** [comment]
@bobzhang Good to know, thanks.

**Comment by not-rusty** [comment]
Closing this as it will be hopefully solved in https://github.com/rescript-lang/rescript-compiler/issues/5303
