### ISSUE TITLE
Generate type for sum of polyvariant constructor

### ISSUE THREAD

**Issue by WhyThat** [rescript-association/genType#577]
Hey there,

Don't know if it's possible, but it could be great to be able to generate type
for sum of polyvariant constructor

giving the following code:
```rescript
type red = [#Ruby | #Redwood | #Rust]
type blue = [#Sapphire | #Neon | #Navy]

export type color = [red | blue]
```
this will generate this
```typescript
/* TypeScript file generated from test.res by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:interface-over-type-literal
export type color = unknown;
```
but it should generate this
```typescript
/* TypeScript file generated from test.res by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:interface-over-type-literal
export type color =
    "Ruby"
  | "Redwood"
  | "Rust"
  | "Sapphire"
  | "Neon"
  | "Navy";
```

So for now, I have to copy every entry in my color type to have a proper
generation, has said, don't know if it's doable, but it could be great if gentype could do this for me :star_struck:

Thanks a lot for this library :)

**Comment by searleser97** [comment]
I beleive it should output

```ts
type red = "Ruby" | "Redwood" | "Rust";

type blue = "Sapphire" | "Neon" | "Navy";

export type color = red | blue;
```

**Comment by cristianoc** [comment]
@WhyThat take a look at https://github.com/rescript-association/genType/pull/578 which handles your examples.

**Comment by WhyThat** [comment]
This seems great :tada:, thanks a lot for the quick fix :)
Do you have any ideas of when you can release it ?

**Comment by cristianoc** [comment]
@WhyThat in release `4.2.2`.
