### ISSUE TITLE
`Text` or `Error` module is not used properly

### ISSUE THREAD

**Issue by tsnobip** [rescript-association/genType#583]
```res
// inside file `Styles.res`
module Text = {
  let foo = "foo"
}
```
produces the following JS:
```js
var $$Text = {
  foo: "foo"
};

exports.$$Text = $$Text;
```
But GenType doesn't seem to know about the name mangling and produces this:
```ts
// @ts-ignore: Implicit any on import
import * as StylesBS__Es6Import from './Styles.mjs';
const StylesBS: any = StylesBS__Es6Import;

export const Text_foo: string = StylesBS.Text.mono;

export const Text: {
  foo: string; 
} = StylesBS.Text
```
Which inevitably produces an error 
```
`StylesBS.Text` is undefined.
```

The same thing happens if you name your module `Error`.

edit: this seems to happen for all the words from rescript [keyword list](https://github.com/rescript-lang/rescript-compiler/blob/88645d034c663cd692e81ff6ffc15aadae0e165d/jscomp/keywords.list).

**Comment by wokalski** [comment]
I love genType but this issue has bitten us so many times now it's impossible to count all the times.

**Comment by ryyppy** [comment]
This repository is being archived. If you feel like the issue still relevant, please re-create it in the [compiler repo](https://github.com/rescript-lang/rescript-compiler). Thanks!
