### ISSUE TITLE
Unused named function paramater causes `rescript build -w` to enter an infinite loop

### ISSUE THREAD

**Issue by tom-sherman** [rescript-association/genType#584]
The following module causes ReScript's watch mode to enter an infinite loop

```rescript
@genType
let y = 5

let x = (a, ~b) => a
```

Repro: 

1. Checkout https://github.com/tom-sherman/rescript-watch-infinite-loop-bug
2. `npm i`
3. `npm start`

Removing or using the unused param stops the loop.

**Comment by a-c-sreedhar-reddy** [comment]
Hey @tom-sherman I tried your repo and watch mode did not enter an infinite loop.

**Comment by tom-sherman** [comment]
@a-c-sreedhar-reddy what OS? I'm in macOS 11.6

**Comment by a-c-sreedhar-reddy** [comment]
yeah I am also on macOS 11.6

**Comment by tom-sherman** [comment]
https://user-images.githubusercontent.com/9257001/147350957-f5aaaacd-3a70-4770-8173-987042677a44.mov

Very strange...

**Comment by a-c-sreedhar-reddy** [comment]
Node v14.18.0
npm 6.14.15

**Comment by cristianoc** [comment]
Caused by an interaction of generatedFileExtension": ".gen.ts"
and the compilers watcher.
There was an issue on this already, which has moved to the compiler repo.

**Comment by ryyppy** [comment]
This repository is being archived. If you feel like the issue still relevant, please re-create it in the [compiler repo](https://github.com/rescript-lang/rescript-compiler). Thanks!
