### ISSUE TITLE
Variant incorrect generated type

### ISSUE THREAD

**Issue by tom-sherman** [rescript-association/genType#585]
First raised on the forum here: https://forum.rescript-lang.org/t/gentype-different-representation-in-rescript-compared-to-generated-typescript/2750

Repro:

Given the following module https://github.com/tom-sherman/rescript-xstate/blob/0e97ec7ef321ceb6408ad52cf7b245f7cfdc6f13/src/XStateFunctor.res

```rescript
@genType
type rec stateNode<'state, 'event> =
  | State({name: 'state, on: array<('event, 'state)>})
  | Compound({name: 'state, children: array<stateNode<'state, 'event>>, initial: 'state})
  | Final({name: 'state})

@genType
type stateList<'state, 'event> = array<stateNode<'state, 'event>>
```

It outputs this typescript

```ts
export type stateNode<state,event> = 
    { tag: "State"; value: { readonly name: state; readonly on: Array<[event, state]> } }
  | { tag: "Compound"; value: {
  readonly name: state; 
  readonly children: stateNode<state,event>[]; 
  readonly initial: state
} }
  | { tag: "Final"; value: { readonly name: state } };

// tslint:disable-next-line:interface-over-type-literal
export type stateList<state,event> = stateNode<state,event>[];
```

However this type is incorrect, as the values of the `stateNode` variant is something like:

```
{ TAG: 0, name: 'idle', on: [ [ 'FETCH', 'loading' ] ] }
```

Differences:

- `TAG` vs `tag`
- Tag values are integers vs the variant constructor names
- Variant payload is nested in a `value` field vs existing as properties at the top level of the object

**Comment by a-c-sreedhar-reddy** [comment]
Hi,

Yeah the representation of variants in the generated javascript and the typescript are not same. But this would not break the app and is type safe.

For the following ReScript code
```res
@genType
type rec stateNode<'state, 'event> =
  | State({name: 'state, on: array<('event, 'state)>})
  | Compound({name: 'state, children: array<stateNode<'state, 'event>>, initial: 'state})
  | Final({name: 'state})

@genType
let logStateNode = (a: stateNode<string, string>) => Js.log(a)
```
The generated typescript bindings are 

```ts
/* TypeScript file generated from Test2.res by genType. */
/* eslint-disable import/first */


// @ts-ignore: Implicit any on import
import * as Test2BS__Es6Import from './Test2.bs';
const Test2BS: any = Test2BS__Es6Import;

// tslint:disable-next-line:interface-over-type-literal
export type stateNode<state,event> = 
    { tag: "State"; value: { readonly name: state; readonly on: Array<[event, state]> } }
  | { tag: "Compound"; value: {
  readonly name: state; 
  readonly children: stateNode<state,event>[]; 
  readonly initial: state
} }
  | { tag: "Final"; value: { readonly name: state } };

export const logStateNode: (a:stateNode<string,string>) => void = function (Arg1: any) {
  const result = 
/* WARNING: circular type stateNode. Only shallow converter applied. */
  Test2BS.logStateNode(Arg1.tag==="State"
    ? Object.assign({TAG: 0}, Arg1.value)
    : Arg1.tag==="Compound"
    ? Object.assign({TAG: 1}, Arg1.value)
    : Object.assign({TAG: 2}, Arg1.value));
  return result
};
```

So genType generated bindings are in such a way that it `accepts the typescript type representation` and then `converts them to ReScript representation` before passing to rescript functions.

**Comment by cristianoc** [comment]
Note There's a warning:
`/* WARNING: circular type stateNode. Only shallow converter applied. */`

The conversion is not supported for recursive types. Because of complexity and unclear semantics. It would at best make a deep copy, lose sharing, etc.

**Comment by err0r500** [comment]
I think I've the same problem. I use [ts-pattern](https://github.com/gvergnaud/ts-pattern) in order to handle output of a rescript function. 

In my case it's based on a `Belt.result.t<'a, 'e>`.

the generated typescript gives me a 
```
type MyResult<a,e> = 
    { tag: "Ok"; value: a }
  | { tag: "Error"; value: e };
```
so I can pattern match on it (typescript side) with 
```
match(result)
	 .with({ tag: "Ok" }, () => ...)
     .with({ tag: "Error"}, () => ...)
```
but it breaks at runtime because it receives something like `{"TAG":1,"_0":0}`

do you know how I can overcome this (without handling the result in rescript)

**Comment by gravitao** [comment]
I received the same error as @err0r500 when using gentype on a record containing attributes with polymorphic variant type values. In my case the workaround was to just not use a polymorphic variant type for these attributes.

This produced the same error as above, and more problematically, objects using this type lost the reference to the original javascript object (mutable attributes in a rescript record) so referential updates weren't propagated:

```res
type loadState<'t> =
  | Resolved('t)
  | Pending('t)
  | No
```

This was the workaround that removed the error and restored object references for objects using this type:

```res
// Remove polymorphism and spit into two types
type stringLoadState =
  | Resolved(string)
  | Pending(string)
  | No
type streamLoadState =
  | Resolved(StreamType.t)
  | Pending(StreamType.t)
  | No
```

I should also mention that using the normal `.bs.js` output worked as expected in both scenarios (i.e.- object references were preserved), but definitely not ideal and would prefer to use the working gentype output.

**Comment by BlueHotDog** [comment]
> Hi,
> 
> Yeah the representation of variants in the generated javascript and the typescript are not same. But this would not break the app and is type safe.
> 
> So genType generated bindings are in such a way that it `accepts the typescript type representation` and then `converts them to ReScript representation` before passing to rescript functions.
> 
> For the following ReScript code
> 
> ```rescript
> @genType
> type rec stateNode<'state, 'event> =
>   | State({name: 'state, on: array<('event, 'state)>})
>   | Compound({name: 'state, children: array<stateNode<'state, 'event>>, initial: 'state})
>   | Final({name: 'state})
> 
> @genType
> let logStateNode = (a: stateNode<string, string>) => Js.log(a)
> ```
> 
> The generated typescript bindings are
> 
> ```ts
> /* TypeScript file generated from Test2.res by genType. */
> /* eslint-disable import/first */
> 
> 
> // @ts-ignore: Implicit any on import
> import * as Test2BS__Es6Import from './Test2.bs';
> const Test2BS: any = Test2BS__Es6Import;
> 
> // tslint:disable-next-line:interface-over-type-literal
> export type stateNode<state,event> = 
>     { tag: "State"; value: { readonly name: state; readonly on: Array<[event, state]> } }
>   | { tag: "Compound"; value: {
>   readonly name: state; 
>   readonly children: stateNode<state,event>[]; 
>   readonly initial: state
> } }
>   | { tag: "Final"; value: { readonly name: state } };
> 
> export const logStateNode: (a:stateNode<string,string>) => void = function (Arg1: any) {
>   const result = 
> /* WARNING: circular type stateNode. Only shallow converter applied. */
>   Test2BS.logStateNode(Arg1.tag==="State"
>     ? Object.assign({TAG: 0}, Arg1.value)
>     : Arg1.tag==="Compound"
>     ? Object.assign({TAG: 1}, Arg1.value)
>     : Object.assign({TAG: 2}, Arg1.value));
>   return result
> };
> ```

This seems to not work when dealing with interfaces.

**Comment by cristianoc** [comment]
Fixed in compiler v11
