### ISSUE TITLE
Shims in sub-folder

### ISSUE THREAD

**Issue by dmtrKovalenko** [rescript-association/genType#587]
When shims are used in the subfolder types are importing with `./shims/{Module}.shim` without any ability to configure the behavior

My tree 

```
├── bsconfig.json
├── src
│   ├── services
│   │   ├── mediaLoader.bs.js
│   │   ├── mediaLoader.gen.tsx
│   │   └── mediaLoader.res
│   ├── shims
│   │   └── Js.shim.ts
```

And inside services folder I get 

```ts
import type {Js_ArrayBuffer_t as ReScriptJs_Js_ArrayBuffer_t} from './shims/Js.shim';
```

instead of 

```ts
import type {Js_ArrayBuffer_t as ReScriptJs_Js_ArrayBuffer_t} from '../shims/Js.shim';
```

bsconfig.json
```json
"gentypeconfig": {
    "language": "typescript",
    "module": "es6",
    "importPath": "relative",
    "exportInterfaces": false,
    "shims": {
      "Js": "Js",
      "ReScriptJs": "shims/Js"
    },
    "debug": {
      "all": false,
      "basic": false
    }
  }
```

It looks like it is not possible not but required so much

**Comment by ryyppy** [comment]
This repository is being archived. If you feel like the issue still relevant, please re-create it in the [compiler repo](https://github.com/rescript-lang/rescript-compiler). Thanks!
