### ISSUE TITLE
can't be installed on MacOS 12.0.1

### ISSUE THREAD

**Issue by evelant** [rescript-association/genType#590]
`yarn add --dev gentype` fails with

```
 error: executable not found: /Users/myuser/dev/project/app/node_modules/gentype/vendor-darwin/gentype.exe

```

Looks like there's a related closed issue here https://github.com/rescript-association/genType/issues/346

Perhaps because I'm on an M1 Mac? If no static binary can be provided for various platforms what are the build requirements?

Sorry if I'm missing something obvious, I've just discovered ReScript and it looks like a fantastically better alternative to Typescript. This is a bit of a frustrating brick wall I've hit trying to get started.

edit: per the error message, the vendor-darwin folder is indeed empty. Was the last release missing a binary?

**Comment by illusionalsagacity** [comment]
@evelant if you're on yarn v3, or maybe this also exists on earlier versions, the `postinstall.js` script does not seem to run. I've observed this also happening on linux as well. The `gentype.exe` file exists, you need to move it into the `vendor-*` directory manually.

**Comment by ryyppy** [comment]
This repository is being archived. If you feel like the issue still relevant, please re-create it in the [compiler repo](https://github.com/rescript-lang/rescript-compiler). Thanks!
