### ISSUE TITLE
Generate TypeScript docstrings from rescript source

### ISSUE THREAD

**Issue by sgrove** [rescript-association/genType#607]
It'd be nice to be able to pass through docstrings from rescript to TypeScript for consumers on hover, e.g. 

current:
![Screen Shot 2022-07-01 at 15 06 19](https://user-images.githubusercontent.com/35296/176972969-8e50c80e-2465-4067-bee2-06d0756a23fa.png)

with docstring passthrough:
![Screen Shot 2022-07-01 at 15 07 33](https://user-images.githubusercontent.com/35296/176972991-6a43e727-9059-4a6e-9f9c-8a69f06424ae.png)

**Comment by cristianoc** [comment]
Doc strings are attributes in the ast. This would be about just printing them next to the function they're attached to.

**Comment by ryyppy** [comment]
This repository is being archived. If you feel like the issue still relevant, please re-create it in the [compiler repo](https://github.com/rescript-lang/rescript-compiler). Thanks!
