### ISSUE TITLE
genType assumes other ML files are in the same directory

### ISSUE THREAD

**Issue by NatKarmios** [rescript-association/genType#616]
When using types from a local Caml module in a different directory, genType doesn't seem to properly compute the module's location. This leads to erroring TypeScript code.
This isn't a problem when using a type from a ReScript module.

See this repository for an example:
https://github.com/NatKarmios/gentype-wrong-import

**Comment by ryyppy** [comment]
This repository is being archived. If you feel like the issue still relevant, please re-create it in the [compiler repo](https://github.com/rescript-lang/rescript-compiler). Thanks!
